name: Build players.json (skaters only)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * *"   # daily at 09:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
            python -m pip install --upgrade pip
            pip install requests

      - name: Generate players.json (skaters only)
        run: |
            python scripts/build_players.py

      - name: Commit players.json
        run: |
          if [ -n "$(git status --porcelain players.json)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add players.json
            git commit -m "Auto-generate players.json"
          else
            echo "No changes to commit."
          fi

      - name: Push if changed
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
